[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Form handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Identity settings for CMS
[dev]
  framework = "astro"

  